Repository atlp-rwanda/knights-ecomm-fe, pull requests merged in 2024-06, with the labels that each got.

#7 Chore: Setting up Knights React project with vite
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/knights logo.svg
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/components/welcome.tsx
  src/hooks/index.ts
  src/main.tsx
  src/pages/welcomePage.tsx
  src/services/index.ts
  src/styles/App.css
  src/styles/index.css
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: frontend

#9 Chore: configure husky, eslint and prettier
  .eslintrc.cjs
  .husky/pre-commit
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/welcome.tsx
  src/hooks/index.ts
  src/main.tsx
  src/pages/welcomePage.tsx
  src/services/index.ts
  src/styles/App.css
  src/styles/index.css
  vite.config.ts
Labels: frontend

#10 This PR is to Setup project with essential libraries and configurations
  .eslintrc.cjs
  .gitignore
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/Routes/Router.tsx
  src/components/ProductList.tsx
  src/components/welcome.tsx
  src/declaration.d.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/redux/actions/productAction.ts
  src/redux/reducers/productReducer.ts
  src/redux/reducers/rootReducer.ts
  src/redux/store.ts
  src/types/productTypes.ts
  src/vite-env.d.ts
Labels: frontend

#13 Add README for our frontend
  README.md
Labels: frontend

#12 Chore: Install Testing Libraries & Setup CI/CD with GitHub Actions
  .eslintrc.cjs
  .github/workflows/ci.yml
  .gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/Routes/Router.tsx
  src/components/ProductList.tsx
  src/components/welcome.tsx
  src/declaration.d.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/welcomePage.tsx
  src/redux/actions/productAction.ts
  src/redux/reducers/productReducer.ts
  src/redux/reducers/rootReducer.ts
  src/redux/store.ts
  src/styles/index.css
  src/test/App.test.tsx
  src/test/setup.ts
  src/test/utils/test-utils.test.tsx
  src/test/utils/test-utils.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: frontend

#14 implement Docker for project
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  package.json
  src/redux/actions/productAction.ts
  src/test/App.test.tsx
  vite.config.ts
Labels: frontend, Ready for reviews

#23 implement User registration (Vendors and Buyers)
  .eslintrc.cjs
  index.html
  netlify.toml
  package.json
  src/App.tsx
  src/Routes/Router.tsx
  src/components/Footer/Footer.tsx
  src/components/Navbar/Navbar.tsx
  src/components/PageTitle.tsx
  src/images/cart.png
  src/images/gmail.png
  src/images/instagram.png
  src/images/logo.png
  src/images/whatsapp.png
  src/layout/Layout.tsx
  src/lib.d.ts
  src/pages/Authentication/Register.tsx
  src/pages/Authentication/RegisterVendor.tsx
  src/pages/Authentication/VerifyEmail.tsx
  src/react-app-env.d.ts
  src/redux/actions/registerAction.ts
  src/redux/actions/verifyingEmailAction.ts
  src/redux/reducers/registerReducer.ts
  src/redux/reducers/rootReducer.ts
  src/redux/reducers/verifyEmailReducer.ts
  src/styles/App.css
  src/styles/index.css
  src/test/components/Footer/Footer.test.tsx
  src/test/components/Navbar/Navbar.test.tsx
  src/test/pages/Authentication/Register.test.tsx
  src/test/pages/Authentication/RegisterVendor.test.tsx
  src/test/pages/Authentication/VerifyEmail.test.tsx
  src/types/registerType.ts
  src/types/verifyEmailType.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: frontend, Ready for reviews

#30 feat-OTP-2FA
  src/Routes/Router.tsx
  src/assets/iconoir_xmark-circle (2).svg
  src/components/Menu/DesktopMenu.tsx
  src/components/SuspendedAccount/SuspendedAccount.tsx
  src/pages/Authentication/GoogleLoginSuccess.tsx
  src/pages/Authentication/Login.tsx
  src/pages/Authentication/OtpPage.tsx
  src/redux/reducers/authReducer.ts
  src/redux/reducers/rootReducer.ts
  src/redux/reducers/userReducer.ts
  src/test/components/Suspendend/Supended.test.tsx
  src/test/pages/Authentication/GoogleLoginSuccess.test.tsx
  src/test/pages/Authentication/LoginAction.test.tsx
  src/test/pages/Authentication/verifyEmailAction.test.tsx
  src/test/pages/otp.test.tsx
  src/types/registerType.ts
  vite.config.ts
Labels: frontend, Ready for reviews, Highest Priority

#31 ft: This PR enable password reset feature for user
  .gitignore
  index.html
  package.json
  public/knights logo.svg
  src/Routes/Router.tsx
  src/pages/Authentication/ForgotPassword.tsx
  src/pages/Authentication/Login.tsx
  src/pages/Authentication/ResetPassword.tsx
  src/redux/actions/passwordResetActions.ts
  src/redux/reducers/passwordResetReducer.ts
  src/redux/reducers/rootReducer.ts
  src/test/pages/Authentication/ForgotPassword.test.tsx
  src/test/pages/Authentication/ResetPassword.test.tsx
  src/test/redux/actions/passwordResetActions.test.tsx
  src/test/redux/reducers/passwordResetReducer.test.tsx
  tailwind.config.js
Labels: frontend, Ready for reviews, Highest Priority

#35 Feature addition of new product by the vendor
  package.json
  public/1.svg
  public/3.svg
  public/Component 3.svg
  public/Dashboard.svg
  public/notification.svg
  public/search.svg
  public/user-square.svg
  src/App.tsx
  src/Routes/Router.tsx
  src/components/Dashboard/DashboardNavbar/DashboardNavbar.tsx
  src/components/Dashboard/DashboardSideBar/DashboardSideBar.tsx
  src/components/Footer/Footer.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Products/DashboardNewProducts/DashboardNewProducts.tsx
  src/components/Products/DashboardProducts/DashboardProducts.tsx
  src/components/Products/DashboardSingleProduct/DashboardSingleProduct.tsx
  src/components/Products/ProductCard/ProductsCard.tsx
  src/layout/DashboarInnerLayout.tsx
  src/layout/DashboardLayout.tsx
  src/layout/Layout.tsx
  src/layout/MainLayout.tsx
  src/pages/Authentication/ResetPassword.tsx
  src/redux/actions/productAction.ts
  src/redux/reducers/createProductReducer.ts
  src/redux/reducers/getSingleProductReducer.ts
  src/redux/reducers/getVendorProductsReducer.ts
  src/redux/reducers/rootReducer.ts
  src/redux/types/productTypes.ts
  src/test/actions/productActions.test.tsx
  src/test/components/DashboardNavbar/DashboardNavbar.test.tsx
  src/test/components/DashboardSideBar/DashboardSideBar.test.tsx
  src/test/components/ProductCard/ProductCard.test.tsx
  src/test/main.test.tsx
  src/test/pages/Products/DashboardProducts.test.tsx
  src/test/pages/Products/DashboardSingleProduct.test.tsx
  src/test/pages/Products/DashboardVendorNewProduct.test.tsx
  src/test/storeWithCapturedActions.ts
  src/types/productTypes.ts
Labels: frontend, Ready for reviews, Highest Priority

#43 Auto GitHub Release Configuration
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
Labels: frontend, Ready for reviews

#42 feat(landing-page): implementing landing page for client (buyer)
  index.html
  src/Routes/Router.tsx
  src/assets/Close.svg
  src/assets/Menu.svg
  src/assets/Vector.svg
  src/assets/banner_mens 2.svg
  src/assets/list_24dp_FILL0_wght400_GRAD0_opsz24.svg
  src/components/Banners/Banner.tsx
  src/components/Banners/HeroSection.tsx
  src/components/Menu/CategoriesMenu.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/loginComponent.tsx
  src/components/ProductList.tsx
  src/components/Products/ProductCard/ClientProductCard.tsx
  src/components/welcome.tsx
  src/images/arrow 1.svg
  src/images/hand_icon 1.png
  src/images/hero_image 1.png
  src/pages/LandingPage/Home.tsx
  src/pages/welcomePage.tsx
  src/redux/reducers/bannerReducer.ts
  src/redux/reducers/categoryReducer.ts
  src/redux/reducers/rootReducer.ts
  src/styles/index.css
  src/test/App.test.tsx
  src/test/components/Banners/Banner.test.tsx
  src/test/components/DashboardNavbar/DashboardNavbar.test.tsx
  src/test/components/Navbar/Navbar.test.tsx
  src/test/components/ProductCard/clientProductCard.test.tsx
  src/test/pages/Authentication/otp.test.tsx
  src/test/pages/LandingPage/Home.test.tsx
  src/test/redux/reducers/authReducer.test.ts
  src/test/utils/bannerRateTime.test.ts
  src/utils/bannerRateTime.ts
  tailwind.config.js
Labels: frontend, Ready for reviews, Highest Priority

#39 ft: Enable User Product Search feature
  .hintrc
  package.json
  src/Routes/Router.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Pagination.tsx
  src/components/Products/ProductCard/SearchCard.tsx
  src/images/sampleProduct.png
  src/pages/searchPage.tsx
  src/redux/actions/searchAction.ts
  src/redux/reducers/SearchReducer.ts
  src/redux/reducers/createProductReducer.ts
  src/redux/reducers/rootReducer.ts
  src/test/components/Navbar/Navbar.test.tsx
  src/test/components/ProductCard/searchCard.test.tsx
  src/test/components/pagination.test.tsx
  src/test/pages/searchResult.test.tsx
  src/test/redux/actions/searchAction.test.ts
  src/test/redux/reducers/searchReducer.test.tsx
  src/types/searchTypes.ts
  tsconfig.json
Labels: frontend, Ready for reviews, Higher Priority

#38 vendor coupon management
  package.json
  src/assets/done-svgrepo-com.svg
  src/assets/status-failed-svgrepo-com.svg
  src/components/Dashboard/DashboardNavbar/DashboardNavbar.tsx
  src/components/Forms/CouponForm.tsx
  src/components/Popups/ConfirmDeletePopup.tsx
  src/components/Popups/FormPopup.tsx
  src/components/Popups/ListPopup.tsx
  src/components/Popups/Popup.tsx
  src/components/Products/DashboardSingleProduct/DashboardSingleProduct.tsx
  src/components/Products/ProductCoupon/ProductCoupon.tsx
  src/pages/searchPage.tsx
  src/redux/actions/productAction.ts
  src/redux/reducers/getSingleProductReducer.ts
  src/redux/reducers/productReducer.ts
  src/services/FormatDate.ts
  src/services/HttpRequest.ts
  src/services/Request.ts
  src/services/index.ts
  src/services/jwtOperation.ts
  src/test/actions/productActions.test.tsx
  src/test/components/DashboardNavbar/DashboardNavbar.test.tsx
  src/test/components/Menu/DesktopMenu.test.tsx
  src/test/components/Popups/Listpopup.test.tsx
  src/test/components/Popups/Popup.test.tsx
  src/test/components/Popups/ProductCoupon.test.tsx
  src/test/main.test.tsx
  src/test/pages/Products/DashboardSingleProduct.test.tsx
  src/test/pages/Products/DashboardVendorNewProduct.test.tsx
  src/test/utils/formatDate.test.tsx
  src/test/utils/jwtOperation.test.tsx
  src/test/utils/mockStore.ts
  src/types/CouponTypes.ts
  src/types/productTypes.ts
  tailwind.config.js
  tsconfig.json
Labels: frontend, Ready for reviews, High Priority
