Repository atlp-rwanda/knights-ecomm-fe, pull requests merged in 2024-07, with the labels that each got.

#51 Feature updating products item
  src/Routes/Router.tsx
  src/__test__/actions/productActions.test.tsx
  src/__test__/components/Navbar/Navbar.test.tsx
  src/__test__/pages/Products/DashboardUpdateProducts.test.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Products/DashboardEditProducts/DashboardEditProducts.tsx
  src/components/Products/DashboardSingleProduct/DashboardSingleProduct.tsx
  src/redux/actions/productAction.ts
  src/redux/reducers/rootReducer.ts
  src/redux/reducers/updateProductReducer.ts
Labels: frontend, Ready for reviews

#36 Enable to delete a product
  src/Routes/Router.tsx
  src/__test__/actions/productActions.test.tsx
  src/__test__/components/ProductCard/ProductCard.test.tsx
  src/__test__/components/ProductCard/clientProductCard.test.tsx
  src/__test__/components/ProductCard/searchCard.test.tsx
  src/__test__/pages/Products/DashboardDeleteProduct.test.tsx
  src/components/Products/DashboardDeleteProduct/DashboardDeleteProduct.tsx
  src/components/Products/DashboardProducts/DashboardProducts.tsx
  src/components/Products/ProductCard/ProductsCard.tsx
  src/redux/actions/loginAction.ts
  src/redux/actions/productAction.ts
  src/redux/reducers/deleteProductReducer.ts
  src/redux/reducers/rootReducer.ts
Labels: Ready for reviews, Highest Priority

#53 feat-wishlist-management
  package.json
  src/Routes/Router.tsx
  src/__test__/components/ProductCard/clientProductCard.test.tsx
  src/__test__/pages/Authentication/otp.test.tsx
  src/__test__/pages/wishlistPage.test.tsx
  src/__test__/redux/reducers/wishlistReducer.test.tsx
  src/__test__/utils/bannerRateTime.test.ts
  src/__test__/utils/errorHandler.test.ts
  src/__test__/utils/wishlistFunctions/addToWishlist.test.ts
  src/__test__/utils/wishlistFunctions/clearAllFromWishlist.test.ts
  src/__test__/utils/wishlistFunctions/deleteFromWIshlist.test.ts
  src/__test__/utils/wishlistFunctions/fetchWishlist.test.ts
  src/components/Banners/BannerIdentifier.tsx
  src/components/Menu/DesktopMenu.tsx
  src/components/Products/ProductCard/ClientProductCard.tsx
  src/pages/Authentication/OtpPage.tsx
  src/pages/LandingPage/Home.tsx
  src/pages/WishlistPage/WishlistPage.tsx
  src/redux/reducers/rootReducer.ts
  src/redux/reducers/wishlistReducer.ts
  src/utils/bannerRateTime.ts
  src/utils/errorHandler.ts
  src/utils/wishlistFunctions/addProduct.ts
  src/utils/wishlistFunctions/clearAll.ts
  src/utils/wishlistFunctions/deleteWishlistProduct.ts
  src/utils/wishlistFunctions/fetchWishlist.ts
Labels: frontend, Ready for reviews, Highest Priority

#55 Implement Single Product View and Cart management (Guest and User)
  package.json
  src/Routes/Router.tsx
  src/__test__/components/Cart/Cart.test.tsx
  src/__test__/components/Navbar/Navbar.test.tsx
  src/__test__/components/SingleProduct/SingleProduct.test.tsx
  src/__test__/pages/wishlistPage.test.tsx
  src/components/Breadcrumbs/ProductBreadcrumbs.tsx
  src/components/Cart/Cart.tsx
  src/components/Cart/CartSkeletonLoader.tsx
  src/components/Menu/DesktopMenu.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Products/ProductCard/ClientProductCard.tsx
  src/components/Products/ProductCard/SearchCard.tsx
  src/components/SingleProduct/SingleProduct.tsx
  src/components/SingleProduct/SingleProductSkeletonLoader.tsx
  src/pages/Authentication/Login.tsx
  src/pages/Authentication/OtpPage.tsx
  src/redux/actions/cartAction.ts
  src/redux/actions/loginAction.ts
  src/redux/reducers/cartReducer.ts
  src/redux/reducers/getSingleProductReducer.ts
  src/redux/reducers/rootReducer.ts
  src/styles/index.css
  src/types/cartTypes.ts
  tailwind.config.js
Labels: frontend, Ready for reviews, Highest Priority

#62 Implement Chatbot functionalities
  src/__test__/components/Chatbot/Chatbot.test.tsx
  src/components/Chatbot/Chatbot.tsx
  src/layout/MainLayout.tsx
  src/pages/LandingPage/Home.tsx
  src/redux/actions/chatAction.ts
  src/redux/reducers/chatMessagesReducer.ts
  src/redux/reducers/rootReducer.ts
  src/types/chatTypes.ts
Labels: frontend, Ready for reviews

#61 implements create order feature for a buyer
  package.json
  src/Routes/Router.tsx
  src/__test__/components/Cart/Cart.test.tsx
  src/__test__/components/Order/BuyerOrderStatus.test.tsx
  src/__test__/components/Order/CreateOrder.test.tsx
  src/__test__/pages/Orders/SinglebuyerOrder.test.tsx
  src/__test__/redux/actions/createOrderAction.test.ts
  src/__test__/redux/reducers/createOrderReducer.test.ts
  src/components/Cart/Cart.tsx
  src/components/Order/BuyerOrderStatus.tsx
  src/components/Order/CreateOrder.tsx
  src/pages/Orders/BuyerOrders.tsx
  src/pages/Orders/SingleBuyerOrder.tsx
  src/redux/actions/createOrderAction.ts
  src/redux/reducers/buyerOrdersReducer.ts
  src/redux/reducers/createOrderReducer.ts
  src/redux/reducers/rootReducer.ts
Labels: frontend, Ready for reviews

#63 Feat-Admin-Dashbord-Users
  src/Routes/Router.tsx
  src/__test__/components/DashboardSideBar/DashboardSideBar.test.tsx
  src/__test__/components/ProductCard/clientProductCard.test.tsx
  src/__test__/dashbord/adminDashbord/singleUser.test.tsx
  src/__test__/dashbord/adminDashbord/user.test.tsx
  src/__test__/pages/LandingPage/Home.test.tsx
  src/__test__/redux/reducers/wishlistReducer.test.tsx
  src/__test__/utils/formartDate&Time.test.ts
  src/__test__/utils/userStatusFunctions/activateUser.test.ts
  src/__test__/utils/userStatusFunctions/deactivateUser.test.ts
  src/__test__/utils/wishlistFunctions/addToWishlist.test.ts
  src/__test__/utils/wishlistFunctions/deleteFromWIshlist.test.ts
  src/__test__/utils/wishlistFunctions/fetchWishlist.test.ts
  src/assets/Enquiry.svg
  src/components/Dashboard/DashboardNavbar/DashboardNavbar.tsx
  src/components/Dashboard/DashboardSideBar/DashboardSideBar.tsx
  src/components/Dashboard/adminDashbord/SingleUser.tsx
  src/components/Dashboard/adminDashbord/Users.tsx
  src/components/Popups/ConfirmDeletePopup.tsx
  src/components/Products/ProductCard/ClientProductCard.tsx
  src/layout/DashboarInnerLayout.tsx
  src/pages/LandingPage/Home.tsx
  src/utils/formartDate&Time.ts
  src/utils/updateUserStatus/activateUser.ts
  src/utils/updateUserStatus/deactivateUser.ts
  src/utils/wishlistFunctions/fetchWishlist.ts
Labels: frontend, Ready for reviews

#64 This PR is for the addition of Stripe Payment Integration with Payment and Success Routes
  src/Routes/Router.tsx
  src/__test__/components/Order/CreateOrder.test.tsx
  src/__test__/components/ProductCard/ProductCard.test.tsx
  src/__test__/components/payment/payment-form.test.tsx
  src/__test__/components/payment/payment.test.tsx
  src/components/Checkout/CheckoutForm.tsx
  src/components/Checkout/checkout.tsx
  src/components/Order/CreateOrder.tsx
  src/components/Products/ProductCard/ProductsCard.tsx
  src/pages/Cart/checkOutMain.tsx
  src/pages/PaymentOk.tsx
Labels: frontend, Ready for reviews

#70 Implement Profile Page for Vendor and Admin
  src/Routes/Router.tsx
  src/__test__/dashbord/dashboardAccount.test.tsx
  src/components/Dashboard/DashboardAccount/DashboardAccount.tsx
  src/images/cloud-upload.png
  src/images/default.jpg
  src/redux/actions/profileAction.ts
  src/redux/reducers/profileReducer.ts
  src/redux/reducers/rootReducer.ts
  src/types/profileTypes.ts
Labels: frontend, Ready for reviews

#71 Protecting routes
  src/Routes/NotAllowed.tsx
  src/Routes/NotFound.tsx
  src/Routes/ProtectedRoute.tsx
  src/Routes/Router.tsx
  src/__test__/pages/routes.test.tsx
  src/components/Dashboard/DashboardSideBar/DashboardSideBar.tsx
  src/components/Products/DashboardProducts/DashboardProducts.tsx
Labels: Ready for reviews, Highest Priority

#72 Implement In-App-Notificatons
  package.json
  src/__test__/components/DashboardNavbar/DashboardNavbar.test.tsx
  src/__test__/components/Navbar/Navbar.test.tsx
  src/__test__/components/Notification/Notification.test.tsx
  src/__test__/components/Notification/NotificationLayout.test.tsx
  src/__test__/components/Notification/OneNotification.test.tsx
  src/__test__/components/Notification/deleteNotifications.test.ts
  src/__test__/dashbord/dashboardAccount.test.tsx
  src/components/Dashboard/DashboardNavbar/DashboardNavbar.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/NotificationLayout.tsx
  src/components/Notification/OneNotification.tsx
  src/components/Notification/assets/Avatar.svg
  src/components/Notification/assets/Fast delivery.svg
  src/components/Notification/assets/Gift card.svg
  src/components/Notification/assets/Trolley.svg
  src/components/Notification/assets/User.svg
  src/components/Notification/assets/Wishlist.svg
  src/redux/actions/cartAction.ts
  src/redux/reducers/notification.ts
  src/redux/reducers/rootReducer.ts
  src/utils/notificationsFunctios/deleteNotifications.ts
  tailwind.config.js
Labels: frontend, Ready for reviews

#73 #68 Implement vendor and admin order management feature
  index.html
  package.json
  src/Routes/Router.tsx
  src/__test__/components/Order/DashboardOrderManagement/DashboardOrderStatus.test.tsx
  src/__test__/pages/Orders/AdminOrders.test.tsx
  src/__test__/pages/Orders/SingleBuyerOrder.test.tsx
  src/__test__/pages/Orders/SingleVendorOrder.test.tsx
  src/__test__/pages/Orders/VendorOrder.test.tsx
  src/__test__/pages/Orders/singleadminOrder.test.tsx
  src/__test__/redux/actions/cartAction.test.ts
  src/__test__/redux/actions/productAction.test.ts
  src/__test__/redux/actions/registerAction.test.ts
  src/__test__/utils/formartDate&Time.test.ts
  src/__test__/utils/numberFormat.test.ts
  src/components/Dashboard/DashboardNavbar/DashboardNavbar.tsx
  src/components/Dashboard/DashboardSideBar/DashboardSideBar.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Order/DashboardOrderManagement/BuyerInfo.tsx
  src/components/Order/DashboardOrderManagement/DashboardOrderStatus.tsx
  src/components/Order/DashboardOrderManagement/HeaderOrderManagement.tsx
  src/components/Order/DashboardOrderManagement/OrderPagination.tsx
  src/components/Order/DashboardOrderManagement/SideBarOrderStatus.tsx
  src/components/Products/ProductCard/ProductsCard.tsx
  src/layout/DashboardLayout.tsx
  src/pages/Orders/AdminOrders.tsx
  src/pages/Orders/SingleAdminOrder.tsx
  src/pages/Orders/SingleBuyerOrder.tsx
  src/pages/Orders/SingleVendorOrder.tsx
  src/pages/Orders/VendorOrder.tsx
  src/redux/reducers/adminOrdersReducer.ts
  src/redux/reducers/orderStatsReducer.ts
  src/redux/reducers/rootReducer.ts
  src/redux/reducers/vendorOrdersReducer.ts
  src/utils/numberFormat.ts
  tailwind.config.js
  vite.config.ts
Labels: frontend, Ready for reviews

#75 Fix user profile page
  src/Routes/Router.tsx
  src/__test__/dashbord/dashboardAccount.test.tsx
  src/components/Dashboard/DashboardAccount/DashboardAccount.tsx
  src/components/Menu/DesktopMenu.tsx
Labels: frontend, Ready for reviews

#79 fixes hard coded data on vendor products page
  src/__test__/components/ProductCard/ProductCard.test.tsx
  src/__test__/pages/Orders/AdminOrders.test.tsx
  src/__test__/pages/Orders/SingleBuyerOrder.test.tsx
  src/__test__/pages/Orders/VendorOrder.test.tsx
  src/__test__/pages/Orders/singleadminOrder.test.tsx
  src/components/Products/DashboardProducts/DashboardProducts.tsx
  src/components/Products/DashboardSingleProduct/DashboardSingleProduct.tsx
  src/components/Products/ProductCard/ProductsCard.tsx
  src/pages/Orders/AdminOrders.tsx
  src/pages/Orders/SingleAdminOrder.tsx
  src/pages/Orders/SingleBuyerOrder.tsx
  src/pages/Orders/SingleVendorOrder.tsx
  src/pages/Orders/VendorOrder.tsx
Labels: frontend
